security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_COOP:        ROLE_GUEST
        ROLE_GUEST:       ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /gestion/dashboard
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/gestion/[a-z]\w+/new, role: ROLE_COOP}
        - { path: ^/gestion/[a-z]\w+/create, role: ROLE_COOP}
        - { path: ^/gestion/[a-z]\w+/[0-9]([0-9])?([0-9])?/edit, role: ROLE_COOP}
        - { path: ^/gestion/[a-z]\w+/[0-9]([0-9])?([0-9])?/update, role: ROLE_COOP}
        - { path: ^/gestion/[a-z]\w+/[0-9]([0-9])?([0-9])?/delete, role: ROLE_COOP}
        - { path: ^/gestion/[a-z]\w+/[0-9]([0-9])?([0-9])?/reactivate, role: ROLE_COOP}
        - { path: ^/gestion/[a-z]\w+/[0-9]([0-9])?([0-9])?/close, role: ROLE_COOP}
        - { path: ^/gestion/[a-z]\w+/[0-9]([0-9])?([0-9])?/add_sector, role: ROLE_COOP}
        - { path: ^/gestion, role: ROLE_GUEST }
        - { path: ^/admin/, role: ROLE_ADMIN }
