<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BasketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasketRepository extends EntityRepository
{

    public function findBasketByWeekYear($date)
    {
        $em = $this->getEntityManager();
        $dql = "select s from App:Basket s where s.week=:week and  YEAR(s.date)=:year ";
        $query = $em->createQuery($dql);
        $query->setParameter("week", date('W', strtotime($date)));
        $query->setParameter("year", date('Y', strtotime($date)));


        if ($query->getResult()) {

           return $query->getSingleResult();

        }

        return false;
    }

    /**
     * devuelve el listado de cestas anteriores a una fecha dada
     * @return mixed
     */
    public function findMonthlyBasket($date)
    {
        $em = $this->getEntityManager();
        $dql = "SELECT b, YEAR(b.date) as y, MONTH(b.date) as m FROM App:Basket b where b.date <:max_date  GROUP by y,m";
        $query = $em->createQuery($dql);
        $query->setParameter("max_date", $date);

        return $query->getResult();
    }
}
