<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EggRegistryUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EggRegistryUserRepository extends EntityRepository
{
}
