<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FowlDestinationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FowlDestinationRepository extends EntityRepository
{
}
