<?php

namespace App\Repository;

/**
 * HarvestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HarvestRepository extends \Doctrine\ORM\EntityRepository
{
}
