<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
    /**
     * Todas las imágenes asociadas a una entidad anfitriona (media polimórfica
     * por object_class + foreign_key), más recientes primero. Usado por el
     * módulo LAR para la galería de un proyecto (panel y web pública).
     *
     * @param string $objectClass Clase lógica de la entidad (p.ej. "larproject").
     * @param string|int $foreignKey Id de la entidad anfitriona.
     * @return \App\Entity\Image[]
     */
    public function findForObject(string $objectClass, $foreignKey): array
    {
        return $this->createQueryBuilder('i')
            ->andWhere('i.objectClass = :object_class')
            ->andWhere('i.foreignKey = :foreign_key')
            ->setParameter('object_class', $objectClass)
            ->setParameter('foreign_key', (string) $foreignKey)
            ->orderBy('i.created', 'DESC')
            ->getQuery()
            ->getResult();
    }

    /**
     * Foto de portada (la más reciente) de cada entidad anfitriona de una lista,
     * en una sola consulta (evita N+1 al pintar tarjetas con miniatura). Devuelve
     * un mapa foreignKey => Image; las entidades sin foto no aparecen en el mapa.
     *
     * @param string $objectClass Clase lógica de la entidad (p.ej. "larproject").
     * @param int[] $foreignKeys Ids de las entidades anfitrionas.
     * @return array<int, \App\Entity\Image>
     */
    public function findCoversFor(string $objectClass, array $foreignKeys): array
    {
        if (!$foreignKeys) {
            return [];
        }

        $images = $this->createQueryBuilder('i')
            ->andWhere('i.objectClass = :object_class')
            ->andWhere('i.foreignKey IN (:foreign_keys)')
            ->setParameter('object_class', $objectClass)
            ->setParameter('foreign_keys', array_map('strval', $foreignKeys))
            ->orderBy('i.created', 'DESC')
            ->getQuery()
            ->getResult();

        $covers = [];
        foreach ($images as $image) {
            // El primero de cada foreignKey es el más reciente (orderBy created DESC).
            $covers[$image->getForeignKey()] ??= $image;
        }

        return $covers;
    }

    public function findBlogGroupedImages($id,$object_class)
    {
        $em = $this->getEntityManager();
        $dql = "select g from App\\Entity\\Image g where g.foreignKey=:foreign_key and g.objectClass=:object_class  and g.single=:single order by g.created desc";
        $query = $em->createQuery($dql);
        $query->setParameter("foreign_key", $id);
        $query->setParameter("single", 0);
        $query->setParameter("object_class",$object_class);

        return $query->getResult();
    }
}
