<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MovementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovementRepository extends EntityRepository
{
    public function findLastMovement($batch_id)
    {
        $em = $this->getEntityManager();
        $dql = "select m from App\\Entity\\Movement m where m.batch=:batch_id order by m.date desc";
        $query = $em->createQuery($dql);
        $query->setParameter("batch_id", $batch_id);
        $query->setMaxResults(1);

        return $query->getResult();
    }

      public function findMovements($batch_id)
    {
        $em = $this->getEntityManager();
        $dql = "select m from App\\Entity\\Movement m where m.batch=:batch_id order by m.date desc";
        $query = $em->createQuery($dql);
        $query->setParameter("batch_id", $batch_id);


        return $query->getResult();
    }
}
