<?php

namespace App\Repository;

use App\Entity\Product;
use Doctrine\ORM\EntityRepository;

//use Symfony\Component\Validator\Constraints\False;


/**
 * SackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SackRepository extends EntityRepository
{
    public function getPurchase(Product $product)
    {
        $em = $this->getEntityManager();
        $dql = "select p from App\\Entity\\Purchase p where p.product=:product and (p.assigned is null or p.assigned=0) order by p.purchase_date asc";
        $query = $em->createQuery($dql);
        $query->setParameter("product", $product);

        $query->setMaxResults(1);

        if ($query->getOneOrNullResult()) {
            return $query->getSingleResult();
        }

        return false;
    }


    public function findAllMonthExpenses($batch)
    {
        $em = $this->getEntityManager();
        $dql = "select   MONTH(s.delivery_date) as month, YEAR(s.delivery_date)
                  as year_date from App\\Entity\\Sack s where s.batch=:batch";

        $dql .= " group by month,year_date order by year_date,month asc";
        $query = $em->createQuery($dql);

        $query->setParameter("batch", $batch);


        return $query->getResult();
    }

    public function findMonthExpenses($batch, $year, $month)
    {
        $em = $this->getEntityManager();
        $dql = "select  sum(s.total_price) as total , MONTH(s.delivery_date) as month, YEAR(s.delivery_date)
                  as year_date from App\\Entity\\Sack s where s.batch=:batch and  YEAR(s.delivery_date)=:year 
                  and MONTH(s.delivery_date)=:month";

        $dql .= " group by month,year_date order by year_date,month asc";

        $query = $em->createQuery($dql);

        $query->setParameter("batch", $batch);
        $query->setParameter("month", $month);
        $query->setParameter("year", $year);

        $result = $query->getScalarResult();
        return $result[0];
    }


    public function findRelativeExpenses($batch, $period_number,$days)
    {
        $em = $this->getEntityManager();
        $dql = "select  sum(s.total_price) as total 
                   from App\\Entity\\Sack s where s.batch=:batch and  s.delivery_date>=:start_date 
                  and s.delivery_date<:end_date";

        //$dql .= " group by month,year_date order by year_date,month asc";

        $query = $em->createQuery($dql);

        $start_date=date("Y-m-d",strtotime($batch->getPurchaseDate()->format('Y-m-d')."+". ($days*($period_number-1)) ."days"));
        $end_date=date("Y-m-d",strtotime($start_date."+ ".$days." days"));

        $query->setParameter("batch", $batch);
        $query->setParameter("start_date", $start_date);
        $query->setParameter("end_date", $end_date);

        $result = $query->getScalarResult();
        return $result[0];
    }


    public function findFoodEatForBatch($batch, $year, $month, $product)
    {
        $em = $this->getEntityManager();
        $dql = "select  sum(s.weight) as total , MONTH(s.delivery_date) as month, YEAR(s.delivery_date)
                  as year_date from App\\Entity\\Sack s where s.batch=:batch and  YEAR(s.delivery_date)=:year 
                  and MONTH(s.delivery_date)=:month 
                  and s.product=:product ";

        $dql .= " group by month,year_date order by year_date,month asc";

        $query = $em->createQuery($dql);

        $query->setParameter("batch", $batch);
        $query->setParameter("month", $month);
        $query->setParameter("year", $year);
        $query->setParameter("product", $product);

        $result = $query->getScalarResult();
        return $result[0]["total"] ?? 0;
    }


    public function findRelativeFoodEatForBatch($batch, $period_number, $product,$days)
    {
        $em = $this->getEntityManager();
        $dql = "select  sum(s.weight) as total from App\\Entity\\Sack s where s.batch=:batch and 
                      s.delivery_date>=:start_date 
                  and s.delivery_date<:end_date
                  and s.product=:product ";

        //$dql .= " group by month,year_date order by year_date,month asc";

        $query = $em->createQuery($dql);

        $start_date=date("Y-m-d",strtotime($batch->getPurchaseDate()->format('Y-m-d')."+". ($days*($period_number-1)) ."days"));
        $end_date=date("Y-m-d",strtotime($start_date."+ ".$days." days"));

        $query->setParameter("batch", $batch);
        $query->setParameter("start_date", $start_date);
        $query->setParameter("end_date", $end_date);
        $query->setParameter("product", $product);

        $result = $query->getScalarResult();
        return $result[0]["total"] ?? 0;
    }
}
