<?php

namespace Gallinas\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BasketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasketRepository extends EntityRepository
{

    public function findBasketByWeekYear($date)
    {
        $em = $this->getEntityManager();
        $dql = "select s from AppBundle:Basket s where s.week=:week and  YEAR(s.date)=:year ";
        $query = $em->createQuery($dql);
        $query->setParameter("week", date('W', strtotime($date)));
        $query->setParameter("year", date('Y', strtotime($date)));


        if ($query->getResult()) {

           return $query->getSingleResult();

        }

        return false;
    }
}
