<?php

namespace Gallinas\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BatchRepository extends EntityRepository
{
    public function getFeedAmountInInterval($batch, $start_time, $end_time)
    {
        $em = $this->getEntityManager();
        $dql = "select s from AppBundle:Sack s where s.batch=:batch and s.delivery_date >= :start_date and s.delivery_date < :end_date";
        $query = $em->createQuery($dql);
        $query->setParameter("batch", $batch);
        $query->setParameter("start_date", $start_time);
        $query->setParameter("end_date", $end_time);


        $amount = 0;
        if ($query->getResult())
        {

            foreach ($query->getResult() as $sack)
            {
                $amount += $sack->getWeight();
            }

        }

        return $amount;
    }

    public function getFowlsAliveInInterval($batch, $end_time)
    {
        $em = $this->getEntityManager();
        $dql = "select s from AppBundle:Fowl s where s.batch=:batch and (s.put_down_date is null or s.put_down_date > :end_date)";
        $query = $em->createQuery($dql);
        $query->setParameter("batch", $batch);
        $query->setParameter("end_date", $end_time);
        if ($query->getResult())
        {
            return count($query->getResult());
        }

    }

    public function getActiveBatch($product_id)
    {
        $em = $this->getEntityManager();
        $dql = "select s from AppBundle:Batch s where s.batch_status =1  and s.product=:product_id";
        $query = $em->createQuery($dql);
        $query->setParameter("product_id", $product_id);

        if ($query->getResult())
        {
            return count($query->getResult());
        }

    }

    /**
     * @param $product_id
     * @param $year
     * @return array
     * devuelve lotes finalizados según el año y el producto
     */
    public function findByProductYear($product_id, $year)

    {
        $em = $this->getEntityManager();
        $dql = "select s from AppBundle:Batch s where YEAR(s.receipt_date)=:year  and s.product=:product_id and s.batch_status=2";
        $query = $em->createQuery($dql);
        $query->setParameter("product_id", $product_id);
        $query->setParameter("year", $year);

        if ($query->getResult())
        {
            return $query->getResult();
        }

    }

    /**
     * @param $product_id
     * @return array
     * devuelve los años en los que se ha producido algún lote del producto determinado. El lote tiene que estar finalizado para que se contabilice
     */
    public function findYearsInProduction($product_id)
    {
        $em = $this->getEntityManager();
        $dql = "select YEAR(s.receipt_date) as year from AppBundle:Batch s where  s.product=:product_id and s.batch_status=2 GROUP  BY year ORDER BY year desc";
        $query = $em->createQuery($dql);
        $query->setParameter("product_id", $product_id);

        if ($query->getResult())
        {
            return $query->getResult();
        }
    }

    public function findBatchs($product_id, $limit)
    {
        $em = $this->getEntityManager();
        $dql = 'select b from AppBundle:Batch b where b.product=:product_id order by b.id desc';
        $query = $em->createQuery($dql);
        $query->setParameter("product_id", $product_id);
        $query->setMaxResults($limit);

        if ($query->getResult())
        {
            return $query->getResult();
        }
    }
}
