<?php

namespace Gallinas\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends EntityRepository
{
    public function findMedia($media_type, $foreign_key, $object_class, $image_type = null)
    {
        $em = $this->getEntityManager();
        $dql = "select g from AppBundle:" . ucfirst($media_type) . " g where g.foreignKey=:foreign_key and g.objectClass=:object_class ";
        if ($image_type !== null)
        {
            $dql .= ' and g.single=:single ';
        }
        $dql .= " order by g.created desc";
        $query = $em->createQuery($dql);
        $query->setParameter("foreign_key", $foreign_key);
        $query->setParameter("object_class", $object_class);
        if ($image_type !== null)
        {
            $query->setParameter("single", $image_type);
        }

        return $query->getResult();
    }

    public function findPostsBySlug($slug)
    {
        $em = $this->getEntityManager();
        $dql = "select b from AppBundle:Blog b where b.slug=:slug";
        $query = $em->createQuery($dql);
        $query->setParameter('slug', $slug);

        return $query->getSingleResult();

    }


    public function findLatest($limit,$offset=1)
    {
        $em=$this->getEntityManager();
        $dql = 'SELECT p
        FROM AppBundle:Blog p
        ORDER BY p.created DESC';

        $query = $em->createQuery($dql);
        $query->setMaxResults($limit);
        $query->setFirstResult($offset);

        return $query->getResult();

    }

}
