<?php

namespace Gallinas\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompostPileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompostPileRepository extends EntityRepository
{
    public function findActivePile()
    {
        $em = $this->getEntityManager();
        $dql = "select m from AppBundle:CompostPile m order by m.start_date desc";
        $query = $em->createQuery($dql);

        $query->setMaxResults(1);

        if (count($query->getResult()))
        {
            return $query->getSingleResult();
        }

        return null;

    }


}
