<?php

namespace Gallinas\AppBundle\Entity;

/**
 * CropWorkingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CropWorkingRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * devuelve los cultivos activos
     */
    public function findActive()
    {
        $em = $this->getEntityManager();
        $dql = "select s from AppBundle:CropWorking s where s.finish=false";
        $query = $em->createQuery($dql);

        return $query->getResult();
    }
}
