<?php

namespace Gallinas\AppBundle\Entity;

/**
 * CropRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CropRepository extends \Doctrine\ORM\EntityRepository
{
}
