<?php

namespace Gallinas\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * CulturalWorkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CulturalWorkRepository extends EntityRepository
{

}
