<?php

namespace Gallinas\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GiftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GiftRepository extends EntityRepository
{
    public function findTotalProductYearMonth($product, $year,$month,$unity)
    {
        $em = $this->getEntityManager();
        $dql = "select sum(c.amount) as total
        from AppBundle:Gift c where YEAR (c.gift_date)=:year and c.unity=:unity  and c.product=:product
        and MONTH (c.gift_date)=:month ";
        $query = $em->createQuery($dql);
        $query->setParameter("year", $year);
        $query->setParameter("month", $month);
        $query->setParameter("unity", $unity);
        $query->setParameter("product", $product);

        if ($query->getSingleScalarResult())
        {
            return $query->getSingleScalarResult();
        } else
        {
            return "0";
        }
    }
}
