<?php

namespace Gallinas\AppBundle\Entity;

/**
 * LaborRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LaborRepository extends \Doctrine\ORM\EntityRepository
{
}
