<?php

namespace Gallinas\AppBundle\Entity;

/**
 * PatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatchRepository extends \Doctrine\ORM\EntityRepository
{
}
