<?php

namespace Gallinas\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PurchaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseRepository extends EntityRepository
{
    public function findLastFeedDate($product)
    {
        $em = $this->getEntityManager();
        $dql = "select p.purchase_date from AppBundle:Purchase p where p.product=:product order by p.purchase_date desc";
        $query = $em->createQuery($dql);
        $query->setParameter("product", $product);
        $query->setMaxResults(1);

        if ($query->getSingleScalarResult())
        {
            return $query->getSingleScalarResult();
        }
    }


    public function findLastFeedPurchase($product, $offset)
    {
        $em = $this->getEntityManager();
        $dql = "select p from AppBundle:Purchase p where p.product=:product order by p.purchase_date desc";
        $query = $em->createQuery($dql);
        $query->setParameter("product", $product);
        $query->setFirstResult($offset);
        $query->setMaxResults(1);

        return $query->getSingleResult();
    }

    public function findByProductYear($product, $year)
    {
        $em = $this->getEntityManager();

        $dql = "select sum(c.amount) as total from AppBundle:Purchase c where YEAR (c.purchase_date)=:year and c.product=:product";
        $query = $em->createQuery($dql);
        $query->setParameter("year", $year);

        $query->setParameter("product", $product);

        if ($query->getSingleScalarResult())
        {
            return $query->getSingleScalarResult();
        } else
        {
            return "0";
        }
    }


}
