<?php

namespace Gallinas\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
//use Symfony\Component\Validator\Constraints\False;


/**
 * SackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SackRepository extends EntityRepository
{
    public function getPurchase(Product $product)
    {
        $em = $this->getEntityManager();
        $dql = "select p from AppBundle:Purchase p where p.product=:product and (p.assigned is null or p.assigned=0) order by p.purchase_date asc";
        $query = $em->createQuery($dql);
        $query->setParameter("product", $product);

        $query->setMaxResults(1);

        if ($query->getOneOrNullResult())
        {
            return $query->getSingleResult();
        }

        return false;
    }
}
