<?php

namespace Gallinas\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * SectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectorRepository extends EntityRepository
{
    public function getAllSectors($zone)
    {
        $em = $this->getEntityManager();
        $qb = $this->_em->createQueryBuilder();
        $qb->select('u')
            ->from($this->_entityName, 'u');

        if ($zone)
        {
            $qb->where('u.zone = :zone');
            $qb->setParameter("zone", $zone);
        }
        return $qb;
    }

    public function deleteSector($sector_id, $crop_working_id)
    {
        $em = $this->getEntityManager();
        $sql = "delete  from  crop_working_sector WHERE  sector_id=:sector and cropworking_id=:cropworking";

        $params = array('sector'=>$sector_id, 'cropworking'=>$crop_working_id);
        $stmt = $em->getConnection()->prepare($sql);
        $stmt->execute($params);

    }
}
