<?php

namespace Gallinas\AppBundle\Entity;

/**
 * TaskImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskImageRepository extends \Doctrine\ORM\EntityRepository
{
}
