<?php

namespace Gallinas\AppBundle\Entity;

/**
 * TaskTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
